### PR TITLE
Improvement of the HZZ Analysis notebook

### PR DESCRIPTION
**Pull request by hexagonsexagon**
I have restructured the notebook such that the code is more readable and understandable to someone who is new to Python. The notebook has been split up into 3 parts: example 1: Reading data, example 2: Reading Monte-Carlo data, and Final Analysis. The first two examples go over the data analysis for one sample of the data and the Monte-Carlo data respectively, while explaining how the selection rules and weights work. The final portion is the full analysis over the entire data set. I have also included a bonus section on including transverse momentum cuts. The signal significance is compared before and after the momentum cuts. 

I added pedagogical explanations of all relevant physics concepts and also explanations of how the code works throughout the process of the analysis. This includes Feynman diagrams of the important production and decay modes of the Higgs as well as the conceptual basis of the signal analysis. There is also a section on frequently asked questions to answer any remaining queries the viewer may have. 

Closes Issue #50

### CODE REVIEW

**Review by Soap2G — CHANGES_REQUESTED** [review]
Hi @hexagonsexagon and thanks for the PR and great job! I have a preliminary set of comments for this, please find it in this review :D

**Review by marianaiv — COMMENTED** [review]
Thanks for all the work Hexiang! Just a minor comment.
I couldn't load the differences. Aside from Giovanni's comments, on the significance cell it is printing:
```
N_sig = np.float64(30.619236946105957)
N_bg = np.float64(21.52894878387451)
signal_significance = np.float64(2.416305424196965)
```
Can you fix it so that it just prints the rounded number (2 or 3 decimals), without np.float.

**Comment by hexagonsexagon** [comment]
> Hi @hexagonsexagon and thanks for the PR and great job! I'm experiencing a bit of an issue in loading the diff from your updated notebook (`20,160 additions, 387 deletions not shown because the diff is too large. Please use a local Git client to view these changes.`), but based on [this](https://patch-diff.githubusercontent.com/raw/atlas-outreach-data-tools/notebooks-collection-opendata/pull/49.diff) I can provide some preliminary comments. I'm gonna report them below since I'm not managing to have the normal interface for reviews.
> 
> * L7: Why is the title now in H2? We could leave it H1.
> * L21: `https`
> * L70-71: I think that the images are not yet in the repo? I can't see them properly rendered.
> * L94 and following: I'm not sure why we have all these `\n`s here.. No new line is reported in the notebook, at least not in what I can see [here](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/blob/4adaeeb05f54a39588eb24332f626e30e3671b8a/13-TeV-examples/uproot_python/HZZAnalysis.ipynb).
> * L182: Same comment as for Valentina: if people are not using Binder, then this cell is needed. Could we uncomment the relevan lines?
> 
> Last question: given that the PR is requested from a fork, I guess that we are _**not**_ using the `hexagonsexagon-patch-1` branch, correct?

1. Fixed
2. Fixed
3. They will appear once Valentina's pull request is finalised.
4. I use a writing convention in markdown and latex... I break apart new sentences and commas with new lines to make them easier to read. I can remove them if you want.
5. Fixed

**Comment by hexagonsexagon** [comment]
> Thanks for all the work Hexiang! Just a minor comment. I couldn't load the differences. Aside from Giovanni's comments, on the significance cell it is printing:
> 
> ```
> N_sig = np.float64(30.619236946105957)
> N_bg = np.float64(21.52894878387451)
> signal_significance = np.float64(2.416305424196965)
> ```
> 
> Can you fix it so that it just prints the rounded number (2 or 3 decimals), without np.float.

Fixed

**Review by Soap2G — DISMISSED** [review]
Hi @hexagonsexagon, looks good to me. Thank you.

**Review by marianaiv — APPROVED** [review]
Looks good to me. Thanks

**Review by AntonioJC — APPROVED** [review]

**Pull request merged**
