### PR TITLE
New notebook recreating the HZZ analysis using the coffea package

### PR DESCRIPTION
**Pull request by stormsomething**

### CODE REVIEW

**Comment by stormsomething** [comment]
This Jupyter notebook is based on the HZZ analysis example provided in this ATLAS outreach repository. As part of an IRIS-HEP fellow project, I created a version of this analysis that demonstrates the usage of the coffea package and achieves a significant reduction in runtime. The main repository for the project has more information on these runtimes as well as other things I worked on during the fellowship. It can be found at https://github.com/stormsomething/CoffeaHZZAnalysis. Please consider merging this new notebook version if you are interested.

**Comment by artfisica** [comment]
Hi!

Excuses for the delay, we will take a look as soon as possible

But, of course, thank you very much for the contribution!

Arturo

**Comment by artfisica** [comment]
Hi, @stormsomething,

I accept your notebook, thank you very much.
But, can I ask you to please at more comments on how we can run it and other details inside the notebook?
Take a look at the styles of the other notebooks already here.

People, including me, are not familiar with this way to perform the analysis. Therefore, I will kindly ask you to add as many details as you can.

Also, you mentioned this is under an IRIS-HEP project. If you have some references for people to read and get more context of this notebook, can you add those also?

Thanks!

**Comment by stormsomething** [comment]
Hi Arturo.

Thanks for accepting my notebook!
I will try to match my notebook to the style and commenting of the other notebooks in this repository.
There isn't a formal write-up for the IRIS-HEP project at this time, but you can find the description and proposal at https://iris-hep.org/fellows/stormsomething.html.
Should I just include links to that as well as the project repository (linked in previous comment) and the relevant documentation/examples in the notebook as references, or is there something more specific you are looking for?
When I am done with this, should I open a new pull request here?

--Storm

**Pull request merged**
