### PR TITLE
Example JSONs for phoenix

### PR DESCRIPTION
**Pull request by marianaiv**
I added JSONs from other processes so that people can see other examples:

- Top: from `MC_MadGraphPythia8EvtGen_A14NNPDF23_3top_SM`
- Weak boson: from `MC_Sherpa_222_NNPDF30NNLO_ZZZ_4l2v`
- Exotics: from `MC_Pythia8EvtGen_A14NNPDF23LO_Wprime_munu_SSM3000`
- Jet: `MC_Sh_228_yyy_01NLO`
- Higgs: `MC_aMcAtNloPythia8EvtGen_tHjb125_4fl_ZZ4l`

I produced them with the phoenix script locally.

>[!NOTE] 
> The selection is not based on anything. Feel free to suggest other datasets.

### CODE REVIEW

**Comment by zlmarshall** [comment]
Awesome. Are these going to get linked from the main page? Embedded, or do we just make the folder browsable, or...?

The Higgs sample in the topic has a typo (it's H->4l, which is a great choice). 

I don't think there's any reason to *remove* these, so I'd just suggest a few additions:

301204 (Z'->ee)
301209 (Z'->mm)
364710 ("J10")
410470 (vanilla ttbar non-all-had)
346342 (ttH, H->4l, ttbar dilep)

Looks like it's about 20 events of each, which is perfect.

Thank you!
Zach

**Comment by marianaiv** [comment]
I added the suggested samples. Thanks!

The easiest (and maybe the first thing I'll do) is to link them in the tutorial as examples: "If you want to see other events we have for top: these, for jets: .....) and link them. With a bit more time, putting screenshots of the displays and discussing differences could be interesting? still the JSONs would be linked.

What do you think?

**Comment by zlmarshall** [comment]
That sounds perfect to me!

**Review by zlmarshall — APPROVED** [review]

**Review by Soap2G — APPROVED** [review]
👍

**Pull request merged**
