### PR TITLE
Add uproot notebooks

### PR DESCRIPTION
**Pull request by meevans1**

### CODE REVIEW

**Comment by artfisica** [comment]
Hi Meirin,

Thank you very much for this work!

I have a couple of comments to please review before to proceed with the merging:

a) The images that include are called at the end *.png and not *pdf. So, the corresponding cell in each notebook needs to be updated so the pics ca ben visible.

b) Also, I will suggest to include the gif at the top, to keep some uniformity. 

So:

Screenshot 2020-03-30 11 38 55

Screenshot 2020-03-30 11 39 24

**Comment by artfisica** [comment]
c) About MyBinder:

I ran just once, so, the statistic is not good, but, I see that after the installation that all the notebook does, the notebook failed to find UpROOT:

Screenshot 2020-03-30 11 41 07

Even when it is installed correctly:

Screenshot 2020-03-30 11 42 34


Screenshot 2020-03-30 11 43 31


Did you face similar problems?

**Comment by artfisica** [comment]
d) In the VM, the installation took a bit more of time (my internet connection I guess), but it went good :)

In fact, the notebook **HZZAnalysis** runs well :)

Screenshot 2020-03-30 11 53 10


Unfortunately, the **HyyAnalysis** has some issue in a module:
Screenshot 2020-03-30 11 51 23



In all the tests above, I tried several times, turning OFF/ON the notebooks a couple of times.

**Comment by meevans1** [comment]
> Hi Meirin,
> 
> Thank you very much for this work!
> 
> I have a couple of comments to please review before to proceed with the merging:
> 
> a) The images that include are called at the end *.png and not *pdf. So, the corresponding cell in each notebook needs to be updated so the pics ca ben visible.
> 
> b) Also, I will suggest to include the gif at the top, to keep some uniformity.
> 
> So:
> 
> Screenshot 2020-03-30 11 38 55
> 
> Screenshot 2020-03-30 11 39 24

I have made these changes in a new commit

**Comment by meevans1** [comment]
The requirements.txt file should solve this,
so I’ve tried moving the requirements.txt file from the 13-TeV-examples/uproot_python directory to see if that works.
How do you test mybinder before merging?

On 30 Mar 2020, at 10:57, ArturoS <notifications@github.com<mailto:notifications@github.com>> wrote:



c) About MyBinder:

I ran just once, so, the statistic is not good, but, I see that after the installation that all the notebook does, the notebook failed to find UpROOT:

[Screenshot 2020-03-30 11 41 07]<https://user-images.githubusercontent.com/8846121/77899809-63db0d00-727d-11ea-9746-a4406c29ec28.png>

Even when it is installed correctly:

[Screenshot 2020-03-30 11 42 34]<https://user-images.githubusercontent.com/8846121/77899838-705f6580-727d-11ea-950c-4a10132182c7.png>

[Screenshot 2020-03-30 11 43 31]<https://user-images.githubusercontent.com/8846121/77899852-76554680-727d-11ea-8711-71a91cbd1e4f.png>

Did you face similar problems?

**Comment by meevans1** [comment]
> c) About MyBinder:
> 
> I ran just once, so, the statistic is not good, but, I see that after the installation that all the notebook does, the notebook failed to find UpROOT:
> 
> Screenshot 2020-03-30 11 41 07
> 
> Even when it is installed correctly:
> 
> Screenshot 2020-03-30 11 42 34
> 
> Screenshot 2020-03-30 11 43 31
> 
> Did you face similar problems?

This seemed to come from some sort of clash between requirements.txt and environment.yml
so I moved everything from requirements.txt into a single environment.yml
I figured out how to test mybinder before merging and it works for me since commit  #fee0544
@artfisica could you test again please?

**Comment by meevans1** [comment]
> d) In the VM, the installation took a bit more of time (my internet connection I guess), but it went good :)
> 
> In fact, the notebook **HZZAnalysis** runs well :)
> 
> Screenshot 2020-03-30 11 53 10
> 
> Unfortunately, the **HyyAnalysis** has some issue in a module:
> Screenshot 2020-03-30 11 51 23
> 
> In all the tests above, I tried several times, turning OFF/ON the notebooks a couple of times.

I added lmfit to the environment.yml should it should work now since commit [fee0544](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/pull/2/commits/fee0544ef9643d63f32c65184d7b86791f8374e1)
@artfisica could you test in the VM again please?
Or let me know how to test

**Comment by artfisica** [comment]
Hi @meevans1,

Good!
For the record, I was running MyBinder in your master branch.

I explored the notebooks using https://nbviewer.jupyter.org/ and from there you can start MyBinder, or directly in the website https://mybinder.org. In both cases, the URL to the GitHub repository is the only piece you need.


The tests in the VM works well now :)
Screenshot 2020-03-30 13 55 01

**Comment by artfisica** [comment]
I go to try once again in MuBinder.

For the test in the VM, I did the same, I cloned your master branch inside it, and I run the notebooks without any prior setup.

**Comment by artfisica** [comment]
Thanks, @meevans1,

Now the 2 notebooks work for me in the VM and MyBinder (they also took a very similar amount of time in both places :)
The only last comment I can do is to please mention that the nice particle figures come from out friend of ﻿[particle zoo](﻿﻿﻿https://www.particlezoo.net/pages/about)

**Comment by meevans1** [comment]
> Thanks, @meevans1,
> 
> Now the 2 notebooks work for me in the VM and MyBinder (they also took a very similar amount of time in both places :)
> The only last comment I can do is to please mention that the nice particle figures come from out friend of ﻿particle zoo

Hi @artfisica 
I've added a reference to particle zoo in the latest commit [cb0e0ae](https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/pull/2/commits/cb0e0ae49f69c2f64c4f64a2ef2109f4d0e67eb5)

**Comment by artfisica** [comment]
Thank you @meevans1 
* The merge is done.
* I also created a tag v1.1 mentioned the existency of the new notebooks
https://github.com/atlas-outreach-data-tools/notebooks-collection-opendata/releases/tag/v1.1

**Pull request merged**
